publish_mode: editorial_workflow
show_preview_links: true

media_folder: 'static/uploads/images'
public_folder: 'uploads/images'

editor:
  preview: false

# site_url: "localhost:8080"
site_url: 'https://vork-test.netlify.app'

slug:
  clean_accents: true

local_backend: true
backend:
  name: git-gateway
  branch: develop # Branch to update (defaults to master)
  site_domain: https://vork-test.netlify.app
  # accept_roles:
  #   - admin
  #   - editor

collections:
  - name: 'pages'
    label: 'Stránky'
    description: 'Seznam všech stránek webu. Každá stránka definuje používané sekce a atributy pro SEO. Vyplněním Redirect atributu zajistíte, že se nevytvoří stránka, ale provede se přesměrování na specifikovanou URL'
    folder: 'content/pages'
    create: true
    slug: '{{route}}'
    fields:
      - { label: 'Route', name: 'route', widget: 'string' }
      - { label: 'Redirect', name: 'redirect', widget: 'string', required: false }
      - { label: 'Titulek', name: 'pageTitle', widget: 'string' }
      - {
          label: 'Řazení stránky',
          name: 'pageOrder',
          widget: 'number',
          defatult: 0,
          min: 0,
          max: 10,
        }
      - { label: 'SEO Titulek', name: 'seoTitle', widget: 'string' }
      - { label: 'SEO Popisek', name: 'seoDescription', widget: 'string' }
      - {
          label: 'Sekce',
          name: 'sections',
          widget: 'relation',
          multiple: true,
          required: false,
          collection: 'section',
          value_field: 'sectionTitle',
          search_fields: ['sectionTitle', sectionText],
        }

  - name: 'section'
    label: 'Sekce'
    description: 'Stavební blok každé stránky'
    folder: 'content/sections'
    create: true
    slug: '{{hiddenTitle}}-{{sectionTitle}}'
    identifier_field: 'sectionTitle'
    fields:
      - { label: 'Titulek', name: 'sectionTitle', widget: 'string', required: false }
      - {
          label: 'Zobrazit titulek sekce',
          name: 'titleVisible',
          widget: 'boolean',
          default: true,
          required: true,
        }
      - { label: 'Text', name: 'sectionText', widget: 'markdown', required: false }
      - {
          label: 'Velikost textu',
          name: 'textSize',
          widget: 'select',
          default: 'normal',
          options: ['normal', 'small'],
          required: false,
        }
      - {
          label: 'Zarovnání',
          name: 'align',
          widget: 'select',
          default: 'center',
          options: ['left', 'center'],
        }
      - { label: 'Tmavé pozadí', name: 'dark', widget: 'boolean', default: false, required: false }
      - {
          label: 'Obrázky',
          name: 'images',
          widget: 'list',
          summary: '{{fields.image}}',
          required: false,
          fields:
            [
              { label: Obrázek, name: image, widget: image },
              { label: Popis, name: imageAlt, widget: string },
            ],
        }
      - {
          label: 'Mód zobrazení obrázků',
          name: 'imagesMode',
          widget: 'select',
          default: 'column',
          options: ['column', 'carousel'],
        }
      - {
          label: 'Články',
          name: 'articles',
          widget: 'relation',
          multiple: true,
          required: false,
          collection: 'article',
          value_field: 'title',
          search_fields: ['title', text],
        }
      - {
          label: 'Claimy',
          name: 'claims',
          widget: 'relation',
          multiple: true,
          required: false,
          collection: 'claim',
          value_field: 'title',
          search_fields: ['title', text],
        }
      - {
          label: 'Lidé',
          name: 'people',
          widget: 'relation',
          multiple: true,
          required: false,
          collection: 'people',
          value_field: 'name',
          search_fields: ['name'],
        }
      - {
          label: 'Produktové kontakty',
          name: 'contactDomains',
          widget: 'relation',
          multiple: true,
          required: false,
          collection: 'contactDomain',
          value_field: 'title',
          search_fields: ['title'],
        }
      - { label: 'Text tlačítka', name: 'buttonText', widget: 'string', required: false }
      - { label: 'Odkaz tlačítka', name: 'buttonLink', widget: 'string', required: false }
      - {
          label: 'Pozice tlačítka',
          name: 'buttonPosition',
          widget: 'select',
          required: false,
          default: 'bottom',
          options: ['top', 'bottom'],
        }

  - name: 'footer'
    label: 'Footer'
    description: 'Patička zobrazená na každé stránce'
    folder: 'content/footer'
    create: false
    slug: 'footer'
    fields:
      - { label: 'Zpět na začátek - text', name: 'backLinkText', widget: 'string' }
      - {
          label: 'Zásady ochrany osobních údajů - text',
          name: 'privateDataProtectionText',
          widget: 'string',
        }
      - {
          label: 'Zásady ochrany osobních údajů - soubor',
          name: 'privateDataProtectionFile',
          widget: 'file',
          allow_multiple: false,
        }
      - {
          label: 'Sítě',
          name: 'networks',
          widget: 'list',
          summary: '{{fields.icon}}',
          fields:
            [
              {
                label: 'Ikona',
                name: 'icon',
                widget: 'select',
                options: ['email', 'facebook', 'instagram', 'linkedin', 'medium', 'phone', 'close'],
              },
              { label: 'Link', name: 'link', widget: 'string' },
            ],
        }

  - name: 'article'
    label: 'Články'
    description: 'Odkazy na psané články'
    folder: 'content/articles'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - { label: 'Text', name: 'text', widget: 'string' }
      - { label: 'Obrázek', name: 'image', widget: 'image' }
      - { label: 'Link', name: 'link', widget: 'string' }

  - name: 'claim'
    label: 'Claimy'
    description: 'Široké pruhy s claimy. Odkazy na specifickou sekci zadávejte ve formě "/nazevStranky#idElementu" nebo celou URL na externí webovou stránku'
    folder: 'content/claims'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - { label: 'Text', name: 'text', widget: 'text' }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Obrázek', name: 'image', widget: 'image', required: false }

  - name: 'people'
    label: 'Lidé'
    description: 'Profily lidí'
    folder: 'content/people'
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Jméno', name: 'name', widget: 'string' }
      - { label: 'Popis', name: 'description', widget: 'text' }
      - { label: 'Fotka', name: 'image', widget: 'image' }
      - { label: 'Linkedin', name: 'linkedin', widget: 'string' }
      - { label: 'Mail', name: 'mail', widget: 'string' }
      - { label: 'Telefon', name: 'phone', widget: 'string' }

  - name: 'contactDomain'
    label: 'Produktové kontakty'
    description: 'Oblasti působení Vorku a kontakty k nim'
    folder: 'content/contactDomains'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Titulek', name: 'title', widget: 'string' }
      - {
          label: 'Lidé',
          name: 'people',
          widget: 'relation',
          multiple: true,
          required: false,
          collection: 'people',
          value_field: 'name',
          search_fields: ['name'],
        }

  - name: 'webConfig'
    label: 'Konfigurace webu'
    description: 'Nastavení obecných atributů webu'
    folder: 'content/webConfig'
    create: false
    slug: 'websiteConfig'
    fields:
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Obecný titulek webu', name: 'title', widget: 'string' }
      - { label: 'Obecný popis', name: 'description', widget: 'text' }
